### ISSUE TITLE
Messages switched to "read" mark automatically

### ISSUE THREAD

**Issue by oyagev** [krerkkiat/nylas-n1-unread-filter#1]
When switching to the special filter with automatic "read" marking, the first message in the list becomes "read" and removed from the list. This cause the next message to become active and then marked "read", and so forth.

The result is that all messages become "read" without actually reading them :-)

**Comment by oyagev** [comment]
oops..

**Comment by krerkkiat** [comment]
Thank you for letting me know that. https://github.com/krerkkiat/nylas-n1-unread-filter/commit/b9785feeaa8bb2c98888a8524f86d84bbe0465d0 should solve that.
